### ISSUE TITLE
Feedback - Week 6 Assignment

### ISSUE THREAD

**Issue by ntuvera** [JasonMartocci/My-Portfolio#4]
Hey @JasonMartocci, I cloned your repo and looked at your Giphy App...

Very nice and clean simple UI layout.  From a UX perspective though, I noticed I can enter blank empy boxes and duplicate boxes which have the same name and same attached images.  For a deployed app, you may want to fix these bugs.  You can easily validate for the empty string .val() with an if/else.  As for the duplicate names, you can either store the previous button names in an array and search then not allow further creation OR have duplicate names appear as new buttons like `cat`, `cat(1)` that load different images.  

Diving into your code...
You didn't use $.ajax.  To be fair we didn't tell you explicitly to use it, but it was expected based on the week's lesson.  Nice use of XMLHttpRequest.    Interesting, not the assignment, but executed well.  I haven't palyed with XMLHttpRequest much lately, so I can't comment too much on it.   But if we used $ajax it will return a JSON object that I'm more comfortable dealing with.  I would like you to use the "javascript" way of doing things since our course will focus on javascript and not really touch XML.  If you're comfortable using XML, get uncomfortable and play with javascript/JSON.  

Lines 33-37 could be "D.R.Y. er"  It's a simple nitpick, but good practice to avoid those extra characters for avoiding bugs and helping other devs read your code.
```
var parsedResponse = JSON.parse(request.responseText)
var slug = parsedResponse.data[i].slug;
var animated = pasredResponse.data[i].images.fixed_height.url;
etc
```

I see you looped through the ```request``` response and gave it a hard limit, but you could also limit the response from the API that way as well, slightly reducing your client side load.  I want you to avoid writing hard limits in your code, it can be referenced to a variable, sure.  But giving hard numbers isn't as dev friendly.  Especially if I want to test the code with some different parameters, or say if I gave your giphy response a limit of 5 for whatever reason.  

Also, why 
```
var image = $('<img src = "'+animated+'"  alt="'+slug+'" class="pause" status="movingImage" id="'+uID+'" title="Rating:'+ rating +'"> ').attr('data-still', still);
```
instead of 
```
var image =$('<img>').attr('src', animated).attr('alt', slug).addClass("pause").attr('status', movingImage)... etc
```
They both work.  The latter is more fo the "jQuery way" to do things.  It also makes it slightly more readable.  There's a blurb somewhere on the internet that says to keep lines of code less than 80 characters when possible.  It makes things easier to read for other devs again.  This is a "coding style", but it's pretty accepted.  Also in terms of readability I chose this line because concatenating your response elements with certain HTML tags is harder to read and more likely prone to errors.  Like with is there a space between ```src```, ```=``` and the ```url```?  It's not breaking anything here on the DOM, but I can't speak for all cases later ;)

I want you to look over $.ajax and try writing something like this again when you have time.  You did an awesome job and showed me some XML, now do it with jQuery lol.  Moving forward you wont see XML much in the course material unless *you* inject it.  I think you're comfortable/familiar with it so no need to use it anymore.

**Comment by JasonMartocci** [comment]
Nate thank you for all the feedback. I made some of the changes. I wasn't sure about lines 33-37 how to make them dryer. If you have a free minute maybe you can let me know what I am missing.

Thank you,
Jason

**Comment by ntuvera** [comment]
```
var slug = JSON.parse(request.responseText).data[i].slug;
        var animated = JSON.parse(request.responseText).data[i].images.fixed_height.url;
        var still = JSON.parse(request.responseText).data[i].images.fixed_height_still.url;
        var rating = JSON.parse(request.responseText).data[i].rating;
        var uID = JSON.parse(request.responseText).data[i].id;
```
vs
```
var parsedResult = JSON.parse(request.responseText).data;
var slug = parsedResult[i].slug;
var animated = parsedResulti].images.fixed_height.url;
var still = parsedResult[i].images.fixed_height_still.url;
var rating = parsedResult[i].rating;
var uID = parsedResult[i].id;
```

**Comment by JasonMartocci** [comment]
I made that change to the file thank you. Much cleaner.
